import Head from 'next/head'
import Reminder from "../components/reminder"

import styles from '../styles/Home.module.css'
import { Provider } from 'react-redux'
import store from "../redux/store"
export default function Home() {
  return (
    <Provider store={store}>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Reminder/>
      </main>

      
    </div>
    </Provider>
  )
}
